config/routes.rb
Rails.application.routes.draw do
  resources :produits

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :produit
end

app/models/produit.rb
class Produit < ActiveRecord::Base
	has_and_belongs_to_many :tags
	has_many :images
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :produit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: [:show, :edit, :update, :destroy]
  before_action :set_big_image, only: [:show]

  # GET /produits
  # GET /produits.json
  def index
    @produits = Produit.all
    @tags = Tag.all
  end

  # GET /produits/1
  # GET /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits
  # POST /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if @produit.save
        format.html { redirect_to @produit, notice: 'Produit was successfully created.' }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1
  # PATCH/PUT /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to @produit, notice: 'Produit was successfully updated.' }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1
  # DELETE /produits/1.json
  def destroy
    @produit.destroy
    respond_to do |format|
      format.html { redirect_to produits_url, notice: 'Produit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    def set_big_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produit_params
      params.require(:produit).permit(:description, :prix, :poids, :tag, :image_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KeleyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produits/_form.html.erb
<%= form_for(@produit) do |f| %>
  <% if @produit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
      <% @produit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :prix %><br>
    <%= f.text_field :prix %>
  </div>
  <div class="field">
    <%= f.label :poids %><br>
    <%= f.text_field :poids %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.number_field :tag %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produits/edit.html.erb
<h1>Editing Produit</h1>

<%= render 'form' %>

<%= link_to 'Show', @produit %> |
<%= link_to 'Back', produits_path %>

app/views/produits/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tbody>
    <tr>
      <td>
        <form>
          <div class="form-group" id="left">
            <label for="filtrer">Filtrer:</label>
            <% @tags.each do |tag| %>
              <div class="radio">
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                   Tag <%= tag.niveau %>
                </label>
              </div>
            <% end %>
          </div>
          <div class="form-group" id="right">
            <label for="tri">Tri par:</label>
            <div class="radio">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                 Prix
              </label>
            </div>
            <div class="radio">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                 Poids
              </label>
            </div>
            <button class="btn btn-default" type="submit">GO</button>
          </div>
        </form>
      </td>
      <td>
        <form name="sform" class="form-inline">
          <input class="form-control" type="text" placeholder="Rechercher">
          <button class="btn btn-default" type="submit">OK</button>
        </form>
      </td>
    </tr>
  </tbody>
</table>
<table class="table">
  <tbody>
    <% @produits.each do |produit| %>
      <tr>
        <td><%= image_tag(produit.images.first.image_url) %></td>
        <td>
          <%= produit.description %>
          <br>
          <% produit.tags.each do |tag| %>
            Tag <%= tag.niveau %>
          <% end %>
        </td>
        <td>
          <%= produit.prix %> euros
        </td>
        <td>
          <%= produit.poids %> kg
          <br>
          <div class="show"><%= link_to 'En savoir plus', produit %></div>
        </td>
        <td><%= produit.tag %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

<%= link_to 'New Produit', new_produit_path %>

app/views/produits/new.html.erb
<h1>New Produit</h1>

<%= render 'form' %>

<%= link_to 'Back', produits_path %>

app/views/produits/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @produit.nom %></h2>
<table class="table">
  <tbody>
      <tr>
        <td>
          <div class="big_image">
            <%= image_tag(@produit.images.first.image_url) %>
          </div>
          <div class="small_image">
            <% @produit.images[1..-1].each do |img| %>
              <%= image_tag(img.image_url) %>
            <%end%>
          </div>
        </td>
        <td>
          <div class="show_left">
            Description:
            <%= @produit.description %>
            <br>
          </div>

          <div class="show_left">
            Poids: <%= @produit.poids %> kg
            <br>
            Prix TTC: <%= @produit.prix %> euros
            <br>
          </div>

          <div class="show_left">
            Catégories attachées:
            <% @produit.tags.each do |tag| %>
              Catégorie <%= tag.niveau %>, 
            <% end %>
          </div>
        </td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_produit_path(@produit) %> |
<%= link_to 'Back', produits_path %>